DOTFILE_DIR="$HOME/.dotfiles"
ZDOTDIR="$HOME/.config/zsh"
HISTFILE="$XDG_STATE_HOME/zsh/history"

[[ -f "$HOME/.zshenv.local" ]] && source "$HOME/.zshenv.local"
[[ -f "$ZDOTDIR/.zshenv.local" ]] && source "$ZDOTDIR/.zshenv.local"
