#!/usr/bin/env zsh

DOTFILE_DIR="$HOME/.dotfiles"
ZSH="$DOTFILE_DIR/zsh/oh-my-zsh"
ZSH_CUSTOM="$DOTFILE_DIR/zsh/custom"
ZDOTDIR="$HOME/.config/zsh"

VIM_DIR="$HOME/.vim"
VIM_BUNDLE_DIR="$HOME/.vim/bundle"
VIM_RUNTIME_DIR="$DOTFILE_DIR/vim/config"

export DOTFILE_DIR ZSH ZSH_CUSTOM ZDOTDIR VIM_DIR VIM_BUNDLE_DIR VIM_RUNTIME_DIR

[[ -f "$HOME/.zshenv.local" ]] && source "$HOME/.zshenv.local"
